name: Auto bump version

on:
  pull_request:
    types: closed

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        #- name: Version - patch
      #  run: sh ./scripts/version.sh patch
      #- run: cat /github/workflow/event.json
      #- name: Dump GitHub context
      #env:
      #GITHUB_CONTEXT: ${{ toJson(github) }}
      #run: echo "${GITHUB_CONTEXT}"
    - name: Bump version
      env:
          PR_LABEL_PATCH: ${{ contains(github.event.pull_request.labels.*.name, 'patch') }}
          PR_LABEL_MAJOR: ${{ contains(github.event.pull_request.labels.*.name, 'major') }}
      if: github.event.action == 'closed' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master'
      run: |
        set -x
        LABEL="minor"
        if ${PR_LABEL_PATCH}; then
            LABEL="patch"
        fi
        if ${PR_LABEL_MAJOR}; then
            LABEL="major"
        fi
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config user.name "${GITHUB_ACTOR}"
        echo "Version Bump"
        npm version ${LABEL}
        git push origin master --follow-tags 

