name: Node.js CI

on:
  pull_request:
    types: closed

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        #- name: Version - patch
      #  run: sh ./scripts/version.sh patch
    - name: If PR is minor
      if: github.event.action == 'closed' && github.event.merged && github.base_ref == 'master' && contains(github.event.pull_request.labels.*.name, 'minor')
      run: sh ./scripts/version.sh minor
