on: push
name: Build and Publish
jobs:
  all:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish
      if: github.ref == 'refs/heads/master'
      uses: fc/merge-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
