name: Release

on:
  pull_request:
    types: closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Tag
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout bill
        uses: actions/checkout@v2
        with:
            repository: altiscope/throwaway-poc-bill-nye
            path: bill-nye
      - name: Checkout beakman
        uses: actions/checkout@v2
        with:
            repository: altiscope/throwaway-poc-beakmans-world
            path: beakmans-world
      - name: Copy artifact and tag release
        run: |
          find .
          cp file  $GITHUB_WORKSPACE/beakmans-world/file
          cd $GITHUB_WORKSPACE
          git add .
          git commit -m Test
          git push
