name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout bill
        uses: actions/checkout@v2
        with:
            repository: altiscope/throwaway-poc-bill-nye
            path: throwaway-poc-bill-nye
      - name: Checkout beakman
        uses: actions/checkout@v2
        with:
            repository: altiscope/throwaway-poc-beakmans-world
            path: throwaway-poc-beakmans-world
      - name: Copy artifact and push
        run: |
          set -x
          cd "${GITHUB_WORKSPACE}/throwaway-poc-bill-nye/"
          VERSION=`git describe --abbrev=0 --tags`
          cd "${GITHUB_WORKSPACE}/throwaway-poc-beakmans-world/"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config user.name "${GITHUB_ACTOR}"
          git config --local --unset-all "http.https://github.com/.extraheader"
          git remote add github "https://${GITHUB_ACTOR}:${PERSONAL_ACCESS_TOKEN}@github.com/altiscope/throwaway-poc-beakmans-world.git"
          git pull github master --ff-only
          cp -f "${GITHUB_WORKSPACE}/throwaway-poc-bill-nye/file" "${GITHUB_WORKSPACE}/throwaway-poc-beakmans-world/file"
          git add "${GITHUB_WORKSPACE}/throwaway-poc-beakmans-world/file"
          git config --list
          git commit -m "release!"
          git tag ${VERSION}
          git push github HEAD:master --tags
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.RELEASE_PAT }}
