name: Release

on:
  pull_request:
    types: closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Tag
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout bill
        uses: actions/checkout@v2
        with:
            repository: altiscope/throwaway-poc-bill-nye
            path: throwaway-poc-bill-nye
      - name: Checkout beakman and copy artifact
        uses: actions/checkout@v2
        with:
            repository: altiscope/throwaway-poc-beakmans-world
            path: throwaway-poc-beakmans-world
      - name: Set GitHub permissions
        uses: actions/checkout@v2
      - name: Copy artifact and tag release
        run: |
          echo ZZZZ
          ls -al .
          echo RRRR
          ls -al ..
          echo QQQQ
          ls -al ../..
          cp -f $GITHUB_WORKSPACE/throwaway-poc-bill-nye/throwaway-poc-bill-nye/file $GITHUB_WORKSPACE/throwaway-poc-beakmans-world/throwaway-poc-beakmans-world/file
          #cd $GITHUB_WORKSPACE/beakmans-world
          #git add $GITHUB_WORKSPACE/beakmans-world/file
          #ls -al $GITHUB_WORKSPACE/beakmans-world
          #git commit -m Test
          #git push
