name: Release

on:
  pull_request:
    types: closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Tag
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout bill
        uses: actions/checkout@v2
        with:
            repository: altiscope/throwaway-poc-bill-nye
            path: throwaway-poc-bill-nye
      - name: Checkout beakman
        uses: actions/checkout@v2
        with:
            repository: altiscope/throwaway-poc-beakmans-world
            path: throwaway-poc-beakmans-world
      - name: Copy artifact and push
        run: |
          cp -f $GITHUB_WORKSPACE/throwaway-poc-bill-nye/file $GITHUB_WORKSPACE/throwaway-poc-beakmans-world/file
          cd ./throwaway-poc-beakmans-world/
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add $GITHUB_WORKSPACE/throwaway-poc-beakmans-world/file
          git commit -m "release!"
          echo "zzz"
          git config --global --unset-all credential.helper
          git config --unset-all credential.helper
          git remote set-url origin https://${PERSONAL_ACCESS_TOKEN}@github.com/altiscope/throwaway-poc-beakmans-world.git
          git remote rm origin
          git remote add origin https://${PERSONAL_ACCESS_TOKEN}@github.com/altiscope/throwaway-poc-beakmans-world.git
          git push --set-upstream origin master
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.RELEASE_PAT }}
