name: Release

on:
  pull_request:
    types: closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Tag
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout bill
        uses: actions/checkout@v2
        with:
            repository: altiscope/throwaway-poc-bill-nye
            path: throwaway-poc-bill-nye
      - name: Checkout beakman
        uses: actions/checkout@v2
        with:
            repository: altiscope/throwaway-poc-beakmans-world
            path: throwaway-poc-beakmans-world
      - name: Copy artifact and push
        run: |
          set -x
          cd ./throwaway-poc-beakmans-world/
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"
          git config http.https://github.com/.extraheader "AUTHORIZATION: basic ${GITHUB_ACTOR}:${PERSONAL_ACCESS_TOKEN}"
          git remote add github "https://github.com/altiscope/throwaway-poc-beakmans-world.git"
          git pull github master --ff-only
          cp -f $GITHUB_WORKSPACE/throwaway-poc-bill-nye/file $GITHUB_WORKSPACE/throwaway-poc-beakmans-world/file
          git add $GITHUB_WORKSPACE/throwaway-poc-beakmans-world/file
          git config --list
          git commit -m "release!"
          echo "zzz"
          git push github HEAD:master
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.RELEASE_PAT }}
