name: Release

on:
  pull_request:
    types: closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Tag
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout bill
        uses: actions/checkout@v2
        with:
            repository: altiscope/throwaway-poc-bill-nye
            path: throwaway-poc-bill-nye
      - name: Checkout beakman and copy artifact
        uses: actions/checkout@v2
        with:
            repository: altiscope/throwaway-poc-beakmans-world
            path: throwaway-poc-beakmans-world
      - name: Copy artifact and tag release
        run: |
          cp -f $GITHUB_WORKSPACE/throwaway-poc-bill-nye/file $GITHUB_WORKSPACE/throwaway-poc-beakmans-world/file
          cd ./throwaway-poc-beakmans-world/
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add $GITHUB_WORKSPACE/throwaway-poc-beakmans-world/file
          git commit -m "release!"
          echo "ZZZ"
          #remote_repo="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/altiscope/throwaway-poc-beakmans-world.git"
          #git push "${remote_repo}" HEAD:master --follow-tags --tags
          #env:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: throwaway-poc-beakmans-world
          repository: throwaway-poc-beakmans-world
          force: true
