name: Release

on:
  pull_request:
    types: closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Tag
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout bill
        uses: actions/checkout@v2
        with:
            repository: altiscope/throwaway-poc-bill-nye
            path: throwaway-poc-bill-nye
      - name: Checkout beakman and copy artifact
        uses: actions/checkout@v2
        with:
            repository: altiscope/throwaway-poc-beakmans-world
            path: throwaway-poc-beakmans-world
      - name: Copy artifact and push
        run: |
          cp -f $GITHUB_WORKSPACE/throwaway-poc-bill-nye/file $GITHUB_WORKSPACE/throwaway-poc-beakmans-world/file
          cd ./throwaway-poc-beakmans-world/
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add $GITHUB_WORKSPACE/throwaway-poc-beakmans-world/file
          git commit -m "release!"
          git remote set-url origin "git@github.com:altiscope/throwaway-poc-beakmans-world.git"
          git push https://${GITHUB_TOKEN}@github.com/altiscope/throwaway-poc-beakmans-world.git
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PAT }}
